[general]
import = ["~/.config/alacritty/lackluster.toml"]

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }

size = 20

[keyboard]
bindings= [
{key= "Back", mods= "Control", chars= "\u0017"},
]

[window]
decorations = "none"

padding.x = 30
padding.y = 30
